//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class NetPosition
    {
        public int InstrumentToken { get; set; }
        public System.DateTime PositionDate { get; set; }
        public string TradingSymbol { get; set; }
        public Nullable<decimal> AveragePrice { get; set; }
        public Nullable<decimal> BuyM2M { get; set; }
        public Nullable<decimal> BuyPrice { get; set; }
        public Nullable<int> BuyQuantity { get; set; }
        public Nullable<decimal> BuyValue { get; set; }
        public Nullable<decimal> ClosePrice { get; set; }
        public string Exchange { get; set; }
        public Nullable<decimal> LastPrice { get; set; }
        public Nullable<decimal> M2M { get; set; }
        public Nullable<decimal> Multiplier { get; set; }
        public Nullable<decimal> NetBuyAmountM2M { get; set; }
        public Nullable<decimal> NetSellAmountM2M { get; set; }
        public Nullable<int> OvernightQuantity { get; set; }
        public Nullable<decimal> PNL { get; set; }
        public string Product { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> Realised { get; set; }
        public Nullable<decimal> SellM2M { get; set; }
        public Nullable<decimal> SellPrice { get; set; }
        public Nullable<int> SellQuantity { get; set; }
        public Nullable<decimal> SellValue { get; set; }
        public Nullable<decimal> Unrealised { get; set; }
        public Nullable<decimal> Value { get; set; }
    }
}
