//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class OHLCData
    {
        public int InstrumentToken { get; set; }
        public System.DateTime OHLCDate { get; set; }
        public System.DateTime LastUpdatedTime { get; set; }
        public string TradingSymbol { get; set; }
        public Nullable<decimal> PreviousClose { get; set; }
        public Nullable<decimal> Open { get; set; }
        public Nullable<decimal> High { get; set; }
        public Nullable<decimal> Low { get; set; }
        public Nullable<decimal> LastPrice { get; set; }
    }
}
