//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TickerRealTimeIndex
    {
        public string IndexName { get; set; }
        public System.DateTime LastTickerTime { get; set; }
        public Nullable<double> Open { get; set; }
        public Nullable<double> High { get; set; }
        public Nullable<double> Low { get; set; }
        public Nullable<double> LTP { get; set; }
        public Nullable<double> Change { get; set; }
        public Nullable<double> ChgPercentage { get; set; }
        public Nullable<double> YearlyChange { get; set; }
        public Nullable<double> MonthlyChange { get; set; }
        public Nullable<double> YearlyHigh { get; set; }
        public Nullable<double> YearlyLow { get; set; }
        public Nullable<int> Advances { get; set; }
        public Nullable<int> Declines { get; set; }
        public Nullable<int> Unchanged { get; set; }
    }
}
