//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TickerMinSuperTrend
    {
        public string StockCode { get; set; }
        public System.DateTime TickerDateTime { get; set; }
        public int TimePeriod { get; set; }
        public Nullable<double> PriceOpen { get; set; }
        public Nullable<double> PriceHigh { get; set; }
        public Nullable<double> PriceLow { get; set; }
        public Nullable<double> PriceClose { get; set; }
        public Nullable<int> Volume { get; set; }
        public Nullable<double> TrueRange { get; set; }
        public Nullable<double> ATR1 { get; set; }
        public Nullable<double> ATR2 { get; set; }
        public Nullable<double> ATR3 { get; set; }
        public Nullable<double> BUB1 { get; set; }
        public Nullable<double> BUB2 { get; set; }
        public Nullable<double> BUB3 { get; set; }
        public Nullable<double> BLB1 { get; set; }
        public Nullable<double> BLB2 { get; set; }
        public Nullable<double> BLB3 { get; set; }
        public Nullable<double> FUB1 { get; set; }
        public Nullable<double> FUB2 { get; set; }
        public Nullable<double> FUB3 { get; set; }
        public Nullable<double> FLB1 { get; set; }
        public Nullable<double> FLB2 { get; set; }
        public Nullable<double> FLB3 { get; set; }
        public Nullable<double> ST1 { get; set; }
        public Nullable<double> ST2 { get; set; }
        public Nullable<double> ST3 { get; set; }
        public string Trend1 { get; set; }
        public string Trend2 { get; set; }
        public string Trend3 { get; set; }
    }
}
