//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TickerRealTimeIndicator
    {
        public int TimePeriod { get; set; }
        public string StockCode { get; set; }
        public System.DateTime PeriodDateTime { get; set; }
        public Nullable<double> Prie { get; set; }
        public Nullable<double> ChangePercentage { get; set; }
        public Nullable<double> TradedVolume { get; set; }
        public Nullable<double> EMA1 { get; set; }
        public Nullable<double> EMA2 { get; set; }
        public Nullable<double> EMA3 { get; set; }
        public Nullable<double> EMA4 { get; set; }
        public Nullable<double> MACD { get; set; }
        public Nullable<double> Signal { get; set; }
        public Nullable<double> Histogram { get; set; }
        public Nullable<double> RSI1 { get; set; }
        public Nullable<double> RSI2 { get; set; }
        public Nullable<double> ForceIndex { get; set; }
        public Nullable<double> OBV { get; set; }
        public Nullable<double> ATR { get; set; }
        public string Impulse { get; set; }
    }
}
