//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TickerRealTimeFO
    {
        public string StockCode { get; set; }
        public System.DateTime TickerDate { get; set; }
        public System.DateTime LastUpdatedTime { get; set; }
        public Nullable<double> Open { get; set; }
        public Nullable<double> High { get; set; }
        public Nullable<double> Low { get; set; }
        public Nullable<double> LTP { get; set; }
        public Nullable<double> Change { get; set; }
        public Nullable<double> ChangePercentage { get; set; }
        public Nullable<double> PreviousClose { get; set; }
        public Nullable<double> DayEndClose { get; set; }
        public Nullable<double> NetTurnOverInCr { get; set; }
        public Nullable<double> TradedVolume { get; set; }
        public Nullable<double> YearlyPercentageChange { get; set; }
        public Nullable<double> MonthlyPercentageChange { get; set; }
    }
}
