//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trade
    {
        public string TradeId { get; set; }
        public string OrderId { get; set; }
        public string ExchangeOrderId { get; set; }
        public string TradingSymbol { get; set; }
        public string Exchange { get; set; }
        public int InstrumentToken { get; set; }
        public string TransactionType { get; set; }
        public string Product { get; set; }
        public decimal AveragePrice { get; set; }
        public int Quantity { get; set; }
        public Nullable<System.DateTime> OrderTimestamp { get; set; }
        public Nullable<System.DateTime> ExchangeTimestamp { get; set; }
    }
}
