//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLogin
    {
        public int ID { get; set; }
        public string Broker { get; set; }
        public string ClientId { get; set; }
        public System.DateTime LoginDateTime { get; set; }
        public System.DateTime LogoutDateTime { get; set; }
        public string RequestToken { get; set; }
        public string AccessToken { get; set; }
        public string PublicToken { get; set; }
        public string Status { get; set; }
    }
}
