//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterStockList
    {
        public int InstrumentToken { get; set; }
        public string TradingSymbol { get; set; }
        public string Name { get; set; }
        public string Collection { get; set; }
        public Nullable<bool> IsIncluded { get; set; }
    }
}
