INSERT INTO MasterStockList VALUES (111111, 'ADANIPORTS','Adani Ports and Special Economic Zone Ltd.','Nifty50', 'SERVICES',1)
INSERT INTO MasterStockList VALUES (111112, 'ASIANPAINT','Asian Paints Ltd.','Nifty50', 'CONSUMER GOODS',1)
INSERT INTO MasterStockList VALUES (111113, 'AXISBANK','Axis Bank Ltd.','Nifty50', 'FINANCIAL SERVICES',1)
INSERT INTO MasterStockList VALUES (111114, 'BAJAJ-AUTO','Bajaj Auto Ltd.','Nifty50', 'AUTOMOBILE',1)
INSERT INTO MasterStockList VALUES (111115, 'BAJFINANCE','Bajaj Finance Ltd.','Nifty50', 'FINANCIAL SERVICES',1)
INSERT INTO MasterStockList VALUES (111116, 'BAJAJFINSV','Bajaj Finserv Ltd.','Nifty50', 'FINANCIAL SERVICES',1)
INSERT INTO MasterStockList VALUES (111117, 'BPCL','Bharat Petroleum Corporation Ltd.','Nifty50', 'ENERGY',1)
INSERT INTO MasterStockList VALUES (111118, 'BHARTIARTL','Bharti Airtel Ltd.','Nifty50', 'TELECOM',1)
INSERT INTO MasterStockList VALUES (111119, 'INFRATEL','Bharti Infratel Ltd.','Nifty50', 'TELECOM',1)
INSERT INTO MasterStockList VALUES (111120, 'BRITANNIA','Britannia Industries Ltd.','Nifty50', 'CONSUMER GOODS',1)
INSERT INTO MasterStockList VALUES (111121, 'CIPLA','Cipla Ltd.','Nifty50', 'PHARMA',1)
INSERT INTO MasterStockList VALUES (111122, 'COALINDIA','Coal India Ltd.','Nifty50', 'METALS',1)
INSERT INTO MasterStockList VALUES (111123, 'DRREDDY','Dr. Reddys Laboratories Ltd.','Nifty50', 'PHARMA',1)
INSERT INTO MasterStockList VALUES (111124, 'EICHERMOT','Eicher Motors Ltd.','Nifty50', 'AUTOMOBILE',1)
INSERT INTO MasterStockList VALUES (111125, 'GAIL','GAIL (India) Ltd.','Nifty50', 'ENERGY',1)
INSERT INTO MasterStockList VALUES (111126, 'GRASIM','Grasim Industries Ltd.','Nifty50', 'CEMENT & CEMENT PRODUCTS',1)
INSERT INTO MasterStockList VALUES (111127, 'HCLTECH','HCL Technologies Ltd.','Nifty50', 'IT',1)
INSERT INTO MasterStockList VALUES (111128, 'HDFCBANK','HDFC Bank Ltd.','Nifty50', 'FINANCIAL SERVICES',1)
INSERT INTO MasterStockList VALUES (111129, 'HEROMOTOCO','Hero MotoCorp Ltd.','Nifty50', 'AUTOMOBILE',1)
INSERT INTO MasterStockList VALUES (111130, 'HINDALCO','Hindalco Industries Ltd.','Nifty50', 'METALS',1)
INSERT INTO MasterStockList VALUES (111131, 'HINDUNILVR','Hindustan Unilever Ltd.','Nifty50', 'CONSUMER GOODS',1)
INSERT INTO MasterStockList VALUES (111132, 'HDFC','Housing Development Finance Corporation Ltd.','Nifty50', 'FINANCIAL SERVICES',1)
INSERT INTO MasterStockList VALUES (111133, 'ICICIBANK','ICICI Bank Ltd.','Nifty50', 'FINANCIAL SERVICES',1)
INSERT INTO MasterStockList VALUES (111134, 'ITC','ITC Ltd.','Nifty50', 'CONSUMER GOODS',1)
INSERT INTO MasterStockList VALUES (111135, 'IOC','Indian Oil Corporation Ltd.','Nifty50', 'ENERGY',1)
INSERT INTO MasterStockList VALUES (111136, 'INDUSINDBK','IndusInd Bank Ltd.','Nifty50', 'FINANCIAL SERVICES',1)
INSERT INTO MasterStockList VALUES (111137, 'INFY','Infosys Ltd.','Nifty50', 'IT',1)
INSERT INTO MasterStockList VALUES (111138, 'JSWSTEEL','JSW Steel Ltd.','Nifty50', 'METALS',1)
INSERT INTO MasterStockList VALUES (111139, 'KOTAKBANK','Kotak Mahindra Bank Ltd.','Nifty50', 'FINANCIAL SERVICES',1)
INSERT INTO MasterStockList VALUES (111140, 'LT','Larsen & Toubro Ltd.','Nifty50', 'CONSTRUCTION',1)
INSERT INTO MasterStockList VALUES (111141, 'M&M','Mahindra & Mahindra Ltd.','Nifty50', 'AUTOMOBILE',1)
INSERT INTO MasterStockList VALUES (111142, 'MARUTI','Maruti Suzuki India Ltd.','Nifty50', 'AUTOMOBILE',1)
INSERT INTO MasterStockList VALUES (111143, 'NTPC','NTPC Ltd.','Nifty50', 'ENERGY',1)
INSERT INTO MasterStockList VALUES (111144, 'NESTLEIND','Nestle India Ltd.','Nifty50', 'CONSUMER GOODS',1)
INSERT INTO MasterStockList VALUES (111145, 'ONGC','Oil & Natural Gas Corporation Ltd.','Nifty50', 'ENERGY',1)
INSERT INTO MasterStockList VALUES (111146, 'POWERGRID','Power Grid Corporation of India Ltd.','Nifty50', 'ENERGY',1)
INSERT INTO MasterStockList VALUES (111147, 'RELIANCE','Reliance Industries Ltd.','Nifty50', 'ENERGY',1)
INSERT INTO MasterStockList VALUES (111148, 'SBIN','State Bank of India','Nifty50', 'FINANCIAL SERVICES',1)
INSERT INTO MasterStockList VALUES (111149, 'SUNPHARMA','Sun Pharmaceutical Industries Ltd.','Nifty50', 'PHARMA',1)
INSERT INTO MasterStockList VALUES (111150, 'TCS','Tata Consultancy Services Ltd.','Nifty50', 'IT',1)
INSERT INTO MasterStockList VALUES (111151, 'TATAMOTORS','Tata Motors Ltd.','Nifty50', 'AUTOMOBILE',1)
INSERT INTO MasterStockList VALUES (111152, 'TATASTEEL','Tata Steel Ltd.','Nifty50', 'METALS',1)
INSERT INTO MasterStockList VALUES (111153, 'TECHM','Tech Mahindra Ltd.','Nifty50', 'IT',1)
INSERT INTO MasterStockList VALUES (111154, 'TITAN','Titan Company Ltd.','Nifty50', 'CONSUMER GOODS',1)
INSERT INTO MasterStockList VALUES (111155, 'UPL','UPL Ltd.','Nifty50', 'FERTILISERS & PESTICIDES',1)
INSERT INTO MasterStockList VALUES (111156, 'ULTRACEMCO','UltraTech Cement Ltd.','Nifty50', 'CEMENT & CEMENT PRODUCTS',1)
INSERT INTO MasterStockList VALUES (111157, 'VEDL','Vedanta Ltd.','Nifty50', 'METALS',1)
INSERT INTO MasterStockList VALUES (111158, 'WIPRO','Wipro Ltd.','Nifty50', 'IT',1)
INSERT INTO MasterStockList VALUES (111159, 'YESBANK','Yes Bank Ltd.','Nifty50', 'FINANCIAL SERVICES',1)
INSERT INTO MasterStockList VALUES (111160, 'ZEEL','Zee Entertainment Enterprises Ltd.','Nifty50', 'MEDIA & ENTERTAINMENT',1)
INSERT INTO MasterStockList VALUES (111161, 'ACC','ACC Ltd.','Next50', 'CEMENT & CEMENT PRODUCTS',1)
INSERT INTO MasterStockList VALUES (111162, 'AMBUJACEM','Ambuja Cements Ltd.','Next50', 'CEMENT & CEMENT PRODUCTS',1)
INSERT INTO MasterStockList VALUES (111163, 'ASHOKLEY','Ashok Leyland Ltd.','Next50', 'AUTOMOBILE',1)
INSERT INTO MasterStockList VALUES (111164, 'AUROPHARMA','Aurobindo Pharma Ltd.','Next50', 'PHARMA',1)
INSERT INTO MasterStockList VALUES (111165, 'DMART','Avenue Supermarts Ltd.','Next50', 'CONSUMER GOODS',1)
INSERT INTO MasterStockList VALUES (111166, 'BAJAJHLDNG','Bajaj Holdings & Investment Ltd.','Next50', 'FINANCIAL SERVICES',1)
INSERT INTO MasterStockList VALUES (111167, 'BANDHANBNK','Bandhan Bank Ltd.','Next50', 'FINANCIAL SERVICES',1)
INSERT INTO MasterStockList VALUES (111168, 'BANKBARODA','Bank of Baroda','Next50', 'FINANCIAL SERVICES',1)
INSERT INTO MasterStockList VALUES (111169, 'BERGEPAINT','Berger Paints India Ltd.','Next50', 'CONSUMER GOODS',1)
INSERT INTO MasterStockList VALUES (111170, 'BIOCON','Biocon Ltd.','Next50', 'PHARMA',1)
INSERT INTO MasterStockList VALUES (111171, 'BOSCHLTD','Bosch Ltd.','Next50', 'AUTOMOBILE',1)
INSERT INTO MasterStockList VALUES (111172, 'CADILAHC','Cadila Healthcare Ltd.','Next50', 'PHARMA',1)
INSERT INTO MasterStockList VALUES (111173, 'COLPAL','Colgate Palmolive (India) Ltd.','Next50', 'CONSUMER GOODS',1)
INSERT INTO MasterStockList VALUES (111174, 'CONCOR','Container Corporation of India Ltd.','Next50', 'SERVICES',1)
INSERT INTO MasterStockList VALUES (111175, 'DLF','DLF Ltd.','Next50', 'CONSTRUCTION',1)
INSERT INTO MasterStockList VALUES (111176, 'DABUR','Dabur India Ltd.','Next50', 'CONSUMER GOODS',1)
INSERT INTO MasterStockList VALUES (111177, 'DIVISLAB','Divis Laboratories Ltd.','Next50', 'PHARMA',1)
INSERT INTO MasterStockList VALUES (111178, 'GICRE','General Insurance Corporation of India','Next50', 'FINANCIAL SERVICES',1)
INSERT INTO MasterStockList VALUES (111179, 'GODREJCP','Godrej Consumer Products Ltd.','Next50', 'CONSUMER GOODS',1)
INSERT INTO MasterStockList VALUES (111180, 'HDFCAMC','HDFC Asset Management Company Ltd.','Next50', 'FINANCIAL SERVICES',1)
INSERT INTO MasterStockList VALUES (111181, 'HDFCLIFE','HDFC Life Insurance Company Ltd.','Next50', 'FINANCIAL SERVICES',1)
INSERT INTO MasterStockList VALUES (111182, 'HAVELLS','Havells India Ltd.','Next50', 'CONSUMER GOODS',1)
INSERT INTO MasterStockList VALUES (111183, 'HINDPETRO','Hindustan Petroleum Corporation Ltd.','Next50', 'ENERGY',1)
INSERT INTO MasterStockList VALUES (111184, 'HINDZINC','Hindustan Zinc Ltd.','Next50', 'METALS',1)
INSERT INTO MasterStockList VALUES (111185, 'ICICIGI','ICICI Lombard General Insurance Company Ltd.','Next50', 'FINANCIAL SERVICES',1)
INSERT INTO MasterStockList VALUES (111186, 'ICICIPRULI','ICICI Prudential Life Insurance Company Ltd.','Next50', 'FINANCIAL SERVICES',1)
INSERT INTO MasterStockList VALUES (111187, 'IBULHSGFIN','Indiabulls Housing Finance Ltd.','Next50', 'FINANCIAL SERVICES',1)
INSERT INTO MasterStockList VALUES (111188, 'INDIGO','InterGlobe Aviation Ltd.','Next50', 'SERVICES',1)
INSERT INTO MasterStockList VALUES (111189, 'L&TFH','L&T Finance Holdings Ltd.','Next50', 'FINANCIAL SERVICES',1)
INSERT INTO MasterStockList VALUES (111190, 'LUPIN','Lupin Ltd.','Next50', 'PHARMA',1)
INSERT INTO MasterStockList VALUES (111191, 'MARICO','Marico Ltd.','Next50', 'CONSUMER GOODS',1)
INSERT INTO MasterStockList VALUES (111192, 'MOTHERSUMI','Motherson Sumi Systems Ltd.','Next50', 'AUTOMOBILE',1)
INSERT INTO MasterStockList VALUES (111193, 'NHPC','NHPC Ltd.','Next50', 'ENERGY',1)
INSERT INTO MasterStockList VALUES (111194, 'NMDC','NMDC Ltd.','Next50', 'METALS',1)
INSERT INTO MasterStockList VALUES (111195, 'OFSS','Oracle Financial Services Software Ltd.','Next50', 'IT',1)
INSERT INTO MasterStockList VALUES (111196, 'PAGEIND','Page Industries Ltd.','Next50', 'TEXTILES',1)
INSERT INTO MasterStockList VALUES (111197, 'PETRONET','Petronet LNG Ltd.','Next50', 'ENERGY',1)
INSERT INTO MasterStockList VALUES (111198, 'PIDILITIND','Pidilite Industries Ltd.','Next50', 'CHEMICALS',1)
INSERT INTO MasterStockList VALUES (111199, 'PEL','Piramal Enterprises Ltd.','Next50', 'PHARMA',1)
INSERT INTO MasterStockList VALUES (111200, 'PFC','Power Finance Corporation Ltd.','Next50', 'FINANCIAL SERVICES',1)
INSERT INTO MasterStockList VALUES (111201, 'PGHH','Procter & Gamble Hygiene & Health Care Ltd.','Next50', 'CONSUMER GOODS',1)
INSERT INTO MasterStockList VALUES (111202, 'PNB','Punjab National Bank','Next50', 'FINANCIAL SERVICES',1)
INSERT INTO MasterStockList VALUES (111203, 'SBILIFE','SBI Life Insurance Company Ltd.','Next50', 'FINANCIAL SERVICES',1)
INSERT INTO MasterStockList VALUES (111204, 'SHREECEM','Shree Cement Ltd.','Next50', 'CEMENT & CEMENT PRODUCTS',1)
INSERT INTO MasterStockList VALUES (111205, 'SRTRANSFIN','Shriram Transport Finance Co. Ltd.','Next50', 'FINANCIAL SERVICES',1)
INSERT INTO MasterStockList VALUES (111206, 'SIEMENS','Siemens Ltd.','Next50', 'INDUSTRIAL MANUFACTURING',1)
INSERT INTO MasterStockList VALUES (111207, 'NIACL','The New India Assurance Company Ltd.','Next50', 'FINANCIAL SERVICES',1)
INSERT INTO MasterStockList VALUES (111208, 'UBL','United Breweries Ltd.','Next50', 'CONSUMER GOODS',1)
INSERT INTO MasterStockList VALUES (111209, 'MCDOWELL-N','United Spirits Ltd.','Next50', 'CONSUMER GOODS',1)
INSERT INTO MasterStockList VALUES (111210, 'IDEA','Vodafone Idea Ltd.','Next50', 'TELECOM',1)
INSERT INTO MasterStockList VALUES (111211, '3MINDIA','3M India Ltd.','Midcap150', 'SERVICES',1)
INSERT INTO MasterStockList VALUES (111212, 'AIAENG','AIA Engineering Ltd.','Midcap150', 'INDUSTRIAL MANUFACTURING',1)
INSERT INTO MasterStockList VALUES (111213, 'AUBANK','AU Small Finance Bank Ltd.','Midcap150', 'FINANCIAL SERVICES',1)
INSERT INTO MasterStockList VALUES (111214, 'AAVAS','Aavas Financiers Ltd.','Midcap150', 'FINANCIAL SERVICES',1)
INSERT INTO MasterStockList VALUES (111215, 'ABBOTINDIA','Abbott India Ltd.','Midcap150', 'PHARMA',1)
INSERT INTO MasterStockList VALUES (111216, 'ADANIGAS','Adani Gas Ltd.','Midcap150', 'ENERGY',1)
INSERT INTO MasterStockList VALUES (111217, 'ADANIPOWER','Adani Power Ltd.','Midcap150', 'ENERGY',1)
INSERT INTO MasterStockList VALUES (111218, 'ADANITRANS','Adani Transmission Ltd.','Midcap150', 'ENERGY',1)
INSERT INTO MasterStockList VALUES (111219, 'ABCAPITAL','Aditya Birla Capital Ltd.','Midcap150', 'FINANCIAL SERVICES',1)
INSERT INTO MasterStockList VALUES (111220, 'ABFRL','Aditya Birla Fashion and Retail Ltd.','Midcap150', 'CONSUMER GOODS',1)
INSERT INTO MasterStockList VALUES (111221, 'AJANTPHARM','Ajanta Pharmaceuticals Ltd.','Midcap150', 'PHARMA',1)
INSERT INTO MasterStockList VALUES (111222, 'APLLTD','Alembic Pharmaceuticals Ltd.','Midcap150', 'PHARMA',1)
INSERT INTO MasterStockList VALUES (111223, 'ALKEM','Alkem Laboratories Ltd.','Midcap150', 'PHARMA',1)
INSERT INTO MasterStockList VALUES (111224, 'ALBK','Allahabad Bank','Midcap150', 'FINANCIAL SERVICES',1)
INSERT INTO MasterStockList VALUES (111225, 'AMARAJABAT','Amara Raja Batteries Ltd.','Midcap150', 'AUTOMOBILE',1)
INSERT INTO MasterStockList VALUES (111226, 'APOLLOHOSP','Apollo Hospitals Enterprise Ltd.','Midcap150', 'HEALTHCARE SERVICES',1)
INSERT INTO MasterStockList VALUES (111227, 'APOLLOTYRE','Apollo Tyres Ltd.','Midcap150', 'AUTOMOBILE',1)
INSERT INTO MasterStockList VALUES (111228, 'ASTRAL','Astral Poly Technik Ltd.','Midcap150', 'INDUSTRIAL MANUFACTURING',1)
INSERT INTO MasterStockList VALUES (111229, 'ATUL','Atul Ltd.','Midcap150', 'CHEMICALS',1)
INSERT INTO MasterStockList VALUES (111230, 'BALKRISIND','Balkrishna Industries Ltd.','Midcap150', 'AUTOMOBILE',1)
INSERT INTO MasterStockList VALUES (111231, 'BANKINDIA','Bank of India','Midcap150', 'FINANCIAL SERVICES',1)
INSERT INTO MasterStockList VALUES (111232, 'BATAINDIA','Bata India Ltd.','Midcap150', 'CONSUMER GOODS',1)
INSERT INTO MasterStockList VALUES (111233, 'BAYERCROP','Bayer Cropscience Ltd.','Midcap150', 'FERTILISERS & PESTICIDES',1)
INSERT INTO MasterStockList VALUES (111234, 'BEL','Bharat Electronics Ltd.','Midcap150', 'INDUSTRIAL MANUFACTURING',1)
INSERT INTO MasterStockList VALUES (111235, 'BHARATFORG','Bharat Forge Ltd.','Midcap150', 'INDUSTRIAL MANUFACTURING',1)
INSERT INTO MasterStockList VALUES (111236, 'BHEL','Bharat Heavy Electricals Ltd.','Midcap150', 'INDUSTRIAL MANUFACTURING',1)
INSERT INTO MasterStockList VALUES (111237, 'BLUEDART','Blue Dart Express Ltd.','Midcap150', 'SERVICES',1)
INSERT INTO MasterStockList VALUES (111238, 'BBTC','Bombay Burmah Trading Corporation Ltd.','Midcap150', 'CONSUMER GOODS',1)
INSERT INTO MasterStockList VALUES (111239, 'CESC','CESC Ltd.','Midcap150', 'ENERGY',1)
INSERT INTO MasterStockList VALUES (111240, 'CRISIL','CRISIL Ltd.','Midcap150', 'FINANCIAL SERVICES',1)
INSERT INTO MasterStockList VALUES (111241, 'CANBK','Canara Bank','Midcap150', 'FINANCIAL SERVICES',1)
INSERT INTO MasterStockList VALUES (111242, 'CASTROLIND','Castrol India Ltd.','Midcap150', 'ENERGY',1)
INSERT INTO MasterStockList VALUES (111243, 'CENTRALBK','Central Bank of India','Midcap150', 'FINANCIAL SERVICES',1)
INSERT INTO MasterStockList VALUES (111244, 'CHOLAHLDNG','Cholamandalam Financial Holdings Ltd.','Midcap150', 'FINANCIAL SERVICES',1)
INSERT INTO MasterStockList VALUES (111245, 'CHOLAFIN','Cholamandalam Investment and Finance Company Ltd.','Midcap150', 'FINANCIAL SERVICES',1)
INSERT INTO MasterStockList VALUES (111246, 'CUB','City Union Bank Ltd.','Midcap150', 'FINANCIAL SERVICES',1)
INSERT INTO MasterStockList VALUES (111247, 'COROMANDEL','Coromandel International Ltd.','Midcap150', 'FERTILISERS & PESTICIDES',1)
INSERT INTO MasterStockList VALUES (111248, 'CORPBANK','Corporation Bank','Midcap150', 'FINANCIAL SERVICES',1)
INSERT INTO MasterStockList VALUES (111249, 'CROMPTON','Crompton Greaves Consumer Electricals Ltd.','Midcap150', 'CONSUMER GOODS',1)
INSERT INTO MasterStockList VALUES (111250, 'CUMMINSIND','Cummins India Ltd.','Midcap150', 'INDUSTRIAL MANUFACTURING',1)
INSERT INTO MasterStockList VALUES (111251, 'DALBHARAT','Dalmia Bharat Ltd.','Midcap150', 'CEMENT & CEMENT PRODUCTS',1)
INSERT INTO MasterStockList VALUES (111252, 'EIHOTEL','EIH Ltd.','Midcap150', 'SERVICES',1)
INSERT INTO MasterStockList VALUES (111253, 'EDELWEISS','Edelweiss Financial Services Ltd.','Midcap150', 'FINANCIAL SERVICES',1)
INSERT INTO MasterStockList VALUES (111254, 'EMAMILTD','Emami Ltd.','Midcap150', 'CONSUMER GOODS',1)
INSERT INTO MasterStockList VALUES (111255, 'ENDURANCE','Endurance Technologies Ltd.','Midcap150', 'AUTOMOBILE',1)
INSERT INTO MasterStockList VALUES (111256, 'ENGINERSIN','Engineers India Ltd.','Midcap150', 'CONSTRUCTION',1)
INSERT INTO MasterStockList VALUES (111257, 'ERIS','Eris Lifesciences Ltd.','Midcap150', 'PHARMA',1)
INSERT INTO MasterStockList VALUES (111258, 'ESCORTS','Escorts Ltd.','Midcap150', 'AUTOMOBILE',1)
INSERT INTO MasterStockList VALUES (111259, 'EXIDEIND','Exide Industries Ltd.','Midcap150', 'AUTOMOBILE',1)
INSERT INTO MasterStockList VALUES (111260, 'FEDERALBNK','Federal Bank Ltd.','Midcap150', 'FINANCIAL SERVICES',1)
INSERT INTO MasterStockList VALUES (111261, 'FORTIS','Fortis Healthcare Ltd.','Midcap150', 'HEALTHCARE SERVICES',1)
INSERT INTO MasterStockList VALUES (111262, 'FCONSUMER','Future Consumer Ltd.','Midcap150', 'CONSUMER GOODS',1)
INSERT INTO MasterStockList VALUES (111263, 'FRETAIL','Future Retail Ltd.','Midcap150', 'CONSUMER GOODS',1)
INSERT INTO MasterStockList VALUES (111264, 'GMRINFRA','GMR Infrastructure Ltd.','Midcap150', 'CONSTRUCTION',1)
INSERT INTO MasterStockList VALUES (111265, 'GILLETTE','Gillette India Ltd.','Midcap150', 'CONSUMER GOODS',1)
INSERT INTO MasterStockList VALUES (111266, 'GLAXO','Glaxosmithkline Pharmaceuticals Ltd.','Midcap150', 'PHARMA',1)
INSERT INTO MasterStockList VALUES (111267, 'GLENMARK','Glenmark Pharmaceuticals Ltd.','Midcap150', 'PHARMA',1)
INSERT INTO MasterStockList VALUES (111268, 'GODREJAGRO','Godrej Agrovet Ltd.','Midcap150', 'CONSUMER GOODS',1)
INSERT INTO MasterStockList VALUES (111269, 'GODREJIND','Godrej Industries Ltd.','Midcap150', 'CONSUMER GOODS',1)
INSERT INTO MasterStockList VALUES (111270, 'GODREJPROP','Godrej Properties Ltd.','Midcap150', 'CONSTRUCTION',1)
INSERT INTO MasterStockList VALUES (111271, 'GRAPHITE','Graphite India Ltd.','Midcap150', 'INDUSTRIAL MANUFACTURING',1)
INSERT INTO MasterStockList VALUES (111272, 'GUJGASLTD','Gujarat Gas Ltd.','Midcap150', 'ENERGY',1)
INSERT INTO MasterStockList VALUES (111273, 'GSPL','Gujarat State Petronet Ltd.','Midcap150', 'ENERGY',1)
INSERT INTO MasterStockList VALUES (111274, 'HEG','H.E.G. Ltd.','Midcap150', 'INDUSTRIAL MANUFACTURING',1)
INSERT INTO MasterStockList VALUES (111275, 'HATSUN','Hatsun Agro Product Ltd.','Midcap150', 'CONSUMER GOODS',1)
INSERT INTO MasterStockList VALUES (111276, 'HEXAWARE','Hexaware Technologies Ltd.','Midcap150', 'IT',1)
INSERT INTO MasterStockList VALUES (111277, 'HAL','Hindustan Aeronautics Ltd.','Midcap150', 'INDUSTRIAL MANUFACTURING',1)
INSERT INTO MasterStockList VALUES (111278, 'HONAUT','Honeywell Automation India Ltd.','Midcap150', 'INDUSTRIAL MANUFACTURING',1)
INSERT INTO MasterStockList VALUES (111279, 'HUDCO','Housing & Urban Development Corporation Ltd.','Midcap150', 'FINANCIAL SERVICES',1)
INSERT INTO MasterStockList VALUES (111280, 'ISEC','ICICI Securities Ltd.','Midcap150', 'FINANCIAL SERVICES',1)
INSERT INTO MasterStockList VALUES (111281, 'IDBI','IDBI Bank Ltd.','Midcap150', 'FINANCIAL SERVICES',1)
INSERT INTO MasterStockList VALUES (111282, 'IDFCFIRSTB','IDFC First Bank Ltd.','Midcap150', 'FINANCIAL SERVICES',1)
INSERT INTO MasterStockList VALUES (111283, 'IBVENTURES','Indiabulls Ventures Ltd.','Midcap150', 'FINANCIAL SERVICES',1)
INSERT INTO MasterStockList VALUES (111284, 'INDIANB','Indian Bank','Midcap150', 'FINANCIAL SERVICES',1)
INSERT INTO MasterStockList VALUES (111285, 'INDHOTEL','Indian Hotels Co. Ltd.','Midcap150', 'SERVICES',1)
INSERT INTO MasterStockList VALUES (111286, 'IOB','Indian Overseas Bank ','Midcap150', 'FINANCIAL SERVICES',1)
INSERT INTO MasterStockList VALUES (111287, 'IGL','Indraprastha Gas Ltd.','Midcap150', 'ENERGY',1)
INSERT INTO MasterStockList VALUES (111288, 'NAUKRI','Info Edge (India) Ltd.','Midcap150', 'IT',1)
INSERT INTO MasterStockList VALUES (111289, 'IPCALAB','Ipca Laboratories Ltd.','Midcap150', 'PHARMA',1)
INSERT INTO MasterStockList VALUES (111290, 'JSWENERGY','JSW Energy Ltd.','Midcap150', 'ENERGY',1)
INSERT INTO MasterStockList VALUES (111291, 'JINDALSTEL','Jindal Steel & Power Ltd.','Midcap150', 'METALS',1)
INSERT INTO MasterStockList VALUES (111292, 'JUBLFOOD','Jubilant Foodworks Ltd.','Midcap150', 'CONSUMER GOODS',1)
INSERT INTO MasterStockList VALUES (111293, 'JUBILANT','Jubilant Life Sciences Ltd.','Midcap150', 'PHARMA',1)
INSERT INTO MasterStockList VALUES (111294, 'KRBL','KRBL Ltd.','Midcap150', 'CONSUMER GOODS',1)
INSERT INTO MasterStockList VALUES (111295, 'KANSAINER','Kansai Nerolac Paints Ltd.','Midcap150', 'CONSUMER GOODS',1)
INSERT INTO MasterStockList VALUES (111296, 'LTTS','L&T Technology Services Ltd.','Midcap150', 'IT',1)
INSERT INTO MasterStockList VALUES (111297, 'LICHSGFIN','LIC Housing Finance Ltd.','Midcap150', 'FINANCIAL SERVICES',1)
INSERT INTO MasterStockList VALUES (111298, 'LTI','Larsen & Toubro Infotech Ltd.','Midcap150', 'IT',1)
INSERT INTO MasterStockList VALUES (111299, 'MRF','MRF Ltd.','Midcap150', 'AUTOMOBILE',1)
INSERT INTO MasterStockList VALUES (111300, 'MGL','Mahanagar Gas Ltd.','Midcap150', 'ENERGY',1)
INSERT INTO MasterStockList VALUES (111301, 'M&MFIN','Mahindra & Mahindra Financial Services Ltd.','Midcap150', 'FINANCIAL SERVICES',1)
INSERT INTO MasterStockList VALUES (111302, 'MAHINDCIE','Mahindra CIE Automotive Ltd.','Midcap150', 'INDUSTRIAL MANUFACTURING',1)
INSERT INTO MasterStockList VALUES (111303, 'MANAPPURAM','Manappuram Finance Ltd.','Midcap150', 'FINANCIAL SERVICES',1)
INSERT INTO MasterStockList VALUES (111304, 'MRPL','Mangalore Refinery & Petrochemicals Ltd.','Midcap150', 'ENERGY',1)
INSERT INTO MasterStockList VALUES (111305, 'MFSL','Max Financial Services Ltd.','Midcap150', 'FINANCIAL SERVICES',1)
INSERT INTO MasterStockList VALUES (111306, 'MINDTREE','MindTree Ltd.','Midcap150', 'IT',1)
INSERT INTO MasterStockList VALUES (111307, 'MOTILALOFS','Motilal Oswal Financial Services Ltd.','Midcap150', 'FINANCIAL SERVICES',1)
INSERT INTO MasterStockList VALUES (111308, 'MPHASIS','MphasiS Ltd.','Midcap150', 'IT',1)
INSERT INTO MasterStockList VALUES (111309, 'MUTHOOTFIN','Muthoot Finance Ltd.','Midcap150', 'FINANCIAL SERVICES',1)
INSERT INTO MasterStockList VALUES (111310, 'NATCOPHARM','NATCO Pharma Ltd.','Midcap150', 'PHARMA',1)
INSERT INTO MasterStockList VALUES (111311, 'NBCC','NBCC (India) Ltd.','Midcap150', 'CONSTRUCTION',1)
INSERT INTO MasterStockList VALUES (111312, 'NLCINDIA','NLC India Ltd.','Midcap150', 'ENERGY',1)
INSERT INTO MasterStockList VALUES (111313, 'NATIONALUM','National Aluminium Co. Ltd.','Midcap150', 'METALS',1)
INSERT INTO MasterStockList VALUES (111314, 'OBEROIRLTY','Oberoi Realty Ltd.','Midcap150', 'CONSTRUCTION',1)
INSERT INTO MasterStockList VALUES (111315, 'OIL','Oil India Ltd.','Midcap150', 'ENERGY',1)
INSERT INTO MasterStockList VALUES (111316, 'ORIENTBANK','Oriental Bank of Commerce','Midcap150', 'FINANCIAL SERVICES',1)
INSERT INTO MasterStockList VALUES (111317, 'PIIND','PI Industries Ltd.','Midcap150', 'FERTILISERS & PESTICIDES',1)
INSERT INTO MasterStockList VALUES (111318, 'PNBHOUSING','PNB Housing Finance Ltd.','Midcap150', 'FINANCIAL SERVICES',1)
INSERT INTO MasterStockList VALUES (111319, 'PFIZER','Pfizer Ltd.','Midcap150', 'PHARMA',1)
INSERT INTO MasterStockList VALUES (111320, 'PHOENIXLTD','Phoenix Mills Ltd.','Midcap150', 'CONSTRUCTION',1)
INSERT INTO MasterStockList VALUES (111321, 'PRESTIGE','Prestige Estates Projects Ltd.','Midcap150', 'CONSTRUCTION',1)
INSERT INTO MasterStockList VALUES (111322, 'QUESS','Quess Corp Ltd.','Midcap150', 'SERVICES',1)
INSERT INTO MasterStockList VALUES (111323, 'RBLBANK','RBL Bank Ltd.','Midcap150', 'FINANCIAL SERVICES',1)
INSERT INTO MasterStockList VALUES (111324, 'RECLTD','REC Ltd.','Midcap150', 'FINANCIAL SERVICES',1)
INSERT INTO MasterStockList VALUES (111325, 'RAJESHEXPO','Rajesh Exports Ltd.','Midcap150', 'CONSUMER GOODS',1)
INSERT INTO MasterStockList VALUES (111326, 'RELAXO','Relaxo Footwears Ltd.','Midcap150', 'CONSUMER GOODS',1)
INSERT INTO MasterStockList VALUES (111327, 'RNAM','Reliance Nippon Life Asset Management Ltd.','Midcap150', 'FINANCIAL SERVICES',1)
INSERT INTO MasterStockList VALUES (111328, 'SJVN','SJVN Ltd.','Midcap150', 'ENERGY',1)
INSERT INTO MasterStockList VALUES (111329, 'SKFINDIA','SKF India Ltd.','Midcap150', 'INDUSTRIAL MANUFACTURING',1)
INSERT INTO MasterStockList VALUES (111330, 'SRF','SRF Ltd.','Midcap150', 'TEXTILES',1)
INSERT INTO MasterStockList VALUES (111331, 'SANOFI','Sanofi India Ltd.','Midcap150', 'PHARMA',1)
INSERT INTO MasterStockList VALUES (111332, 'SHRIRAMCIT','Shriram City Union Finance Ltd.','Midcap150', 'FINANCIAL SERVICES',1)
INSERT INTO MasterStockList VALUES (111333, 'SOLARINDS','Solar Industries India Ltd.','Midcap150', 'CHEMICALS',1)
INSERT INTO MasterStockList VALUES (111334, 'SAIL','Steel Authority of India Ltd.','Midcap150', 'METALS',1)
INSERT INTO MasterStockList VALUES (111335, 'STRTECH','Sterlite Technologies Ltd.','Midcap150', 'TELECOM',1)
INSERT INTO MasterStockList VALUES (111336, 'SUNTV','Sun TV Network Ltd.','Midcap150', 'MEDIA & ENTERTAINMENT',1)
INSERT INTO MasterStockList VALUES (111337, 'SUNDARMFIN','Sundaram Finance Ltd.','Midcap150', 'FINANCIAL SERVICES',1)
INSERT INTO MasterStockList VALUES (111338, 'SUNDRMFAST','Sundram Fasteners Ltd.','Midcap150', 'AUTOMOBILE',1)
INSERT INTO MasterStockList VALUES (111339, 'SUPREMEIND','Supreme Industries Ltd.','Midcap150', 'INDUSTRIAL MANUFACTURING',1)
INSERT INTO MasterStockList VALUES (111340, 'SYMPHONY','Symphony Ltd.','Midcap150', 'CONSUMER GOODS',1)
INSERT INTO MasterStockList VALUES (111341, 'SYNGENE','Syngene International Ltd.','Midcap150', 'PHARMA',1)
INSERT INTO MasterStockList VALUES (111342, 'TTKPRESTIG','TTK Prestige Ltd.','Midcap150', 'CONSUMER GOODS',1)
INSERT INTO MasterStockList VALUES (111343, 'TVSMOTOR','TVS Motor Company Ltd.','Midcap150', 'AUTOMOBILE',1)
INSERT INTO MasterStockList VALUES (111344, 'TATACHEM','Tata Chemicals Ltd.','Midcap150', 'CHEMICALS',1)
INSERT INTO MasterStockList VALUES (111345, 'TATAGLOBAL','Tata Global Beverages Ltd.','Midcap150', 'CONSUMER GOODS',1)
INSERT INTO MasterStockList VALUES (111346, 'TATAPOWER','Tata Power Co. Ltd.','Midcap150', 'ENERGY',1)
INSERT INTO MasterStockList VALUES (111347, 'RAMCOCEM','The Ramco Cements Ltd.','Midcap150', 'CEMENT & CEMENT PRODUCTS',1)
INSERT INTO MasterStockList VALUES (111348, 'THERMAX','Thermax Ltd.','Midcap150', 'INDUSTRIAL MANUFACTURING',1)
INSERT INTO MasterStockList VALUES (111349, 'TORNTPHARM','Torrent Pharmaceuticals Ltd.','Midcap150', 'PHARMA',1)
INSERT INTO MasterStockList VALUES (111350, 'TORNTPOWER','Torrent Power Ltd.','Midcap150', 'ENERGY',1)
INSERT INTO MasterStockList VALUES (111351, 'TRENT','Trent Ltd.','Midcap150', 'CONSUMER GOODS',1)
INSERT INTO MasterStockList VALUES (111352, 'UCOBANK','UCO Bank','Midcap150', 'FINANCIAL SERVICES',1)
INSERT INTO MasterStockList VALUES (111353, 'UNIONBANK','Union Bank of India','Midcap150', 'FINANCIAL SERVICES',1)
INSERT INTO MasterStockList VALUES (111354, 'VGUARD','V-Guard Industries Ltd.','Midcap150', 'CONSUMER GOODS',1)
INSERT INTO MasterStockList VALUES (111355, 'VARROC','Varroc Engineering Ltd.','Midcap150', 'AUTOMOBILE',1)
INSERT INTO MasterStockList VALUES (111356, 'VBL','Varun Beverages Ltd.','Midcap150', 'CONSUMER GOODS',1)
INSERT INTO MasterStockList VALUES (111357, 'VINATIORGA','Vinati Organics Ltd.','Midcap150', 'CHEMICALS',1)
INSERT INTO MasterStockList VALUES (111358, 'VOLTAS','Voltas Ltd.','Midcap150', 'CONSUMER GOODS',1)
INSERT INTO MasterStockList VALUES (111359, 'WABCOINDIA','WABCO India Ltd.','Midcap150', 'AUTOMOBILE',1)
INSERT INTO MasterStockList VALUES (111360, 'WHIRLPOOL','Whirlpool of India Ltd.','Midcap150', 'CONSUMER GOODS',1)
