//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradeGenie.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class ElderBackTesting
    {
        public int InstrumentToken { get; set; }
        public string TradingSymbol { get; set; }
        public System.DateTime TradeDate { get; set; }
        public System.DateTime EntryTime { get; set; }
        public Nullable<System.DateTime> ExitTime { get; set; }
        public Nullable<double> EntryPrice { get; set; }
        public Nullable<double> ExitPrice { get; set; }
        public string OrderType { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<double> EMA1 { get; set; }
        public Nullable<double> EMA2 { get; set; }
        public Nullable<double> EMA1Dev { get; set; }
        public Nullable<double> EMA2Dev { get; set; }
        public Nullable<double> ForceIndex { get; set; }
        public Nullable<double> Histogram { get; set; }
        public string HistogramMovement { get; set; }
        public string Impulse { get; set; }
    }
}
