//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradeGenie.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Margin
    {
        public System.DateTime MarginDate { get; set; }
        public Nullable<bool> Enabled { get; set; }
        public Nullable<decimal> Net { get; set; }
        public Nullable<decimal> AdhocMargin { get; set; }
        public Nullable<decimal> Collateral { get; set; }
        public Nullable<decimal> IntradayPayin { get; set; }
        public Nullable<decimal> Cash { get; set; }
        public Nullable<decimal> M2MUnrealised { get; set; }
        public Nullable<decimal> M2MRealised { get; set; }
        public Nullable<decimal> Debits { get; set; }
        public Nullable<decimal> Span { get; set; }
        public Nullable<decimal> Payout { get; set; }
        public Nullable<decimal> OptionPremium { get; set; }
        public Nullable<decimal> HoldingSales { get; set; }
        public Nullable<decimal> Exposure { get; set; }
        public Nullable<decimal> Turnover { get; set; }
    }
}
