//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradeGenie.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class MorningBreakout
    {
        public int InstrumentToken { get; set; }
        public System.DateTime DateTimePeriod { get; set; }
        public string TradingSymbol { get; set; }
        public Nullable<decimal> Open { get; set; }
        public Nullable<decimal> High { get; set; }
        public Nullable<decimal> Low { get; set; }
        public Nullable<decimal> Close { get; set; }
        public Nullable<decimal> LTP { get; set; }
        public Nullable<decimal> CandleSize { get; set; }
        public Nullable<decimal> DayHigh { get; set; }
        public Nullable<decimal> DayLow { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> Entry { get; set; }
        public Nullable<System.DateTime> EntryTime { get; set; }
        public Nullable<decimal> Exit { get; set; }
        public Nullable<System.DateTime> ExitTime { get; set; }
        public Nullable<decimal> StopLoss { get; set; }
        public Nullable<System.DateTime> StopLossHitTime { get; set; }
        public Nullable<decimal> ProfitLoss { get; set; }
        public string RAGStatus { get; set; }
        public string Movement { get; set; }
        public Nullable<bool> isRealOrderPlaced { get; set; }
    }
}
