//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradeGenie.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class TickerMinEMAHA
    {
        public string StockCode { get; set; }
        public System.DateTime TickerDateTime { get; set; }
        public int TimePeriod { get; set; }
        public Nullable<double> PriceOpen { get; set; }
        public Nullable<double> PriceHigh { get; set; }
        public Nullable<double> PriceLow { get; set; }
        public Nullable<double> PriceClose { get; set; }
        public Nullable<int> Volume { get; set; }
        public Nullable<double> EHEMA1 { get; set; }
        public Nullable<double> EHEMA2 { get; set; }
        public Nullable<double> EHEMA3 { get; set; }
        public Nullable<double> EHEMA4 { get; set; }
        public Nullable<double> EHEMA5 { get; set; }
        public Nullable<double> VWMA1 { get; set; }
        public Nullable<double> VWMA2 { get; set; }
        public Nullable<double> HAOpen { get; set; }
        public Nullable<double> HAHigh { get; set; }
        public Nullable<double> HALow { get; set; }
        public Nullable<double> HAClose { get; set; }
        public Nullable<double> varEMA1v2 { get; set; }
        public Nullable<double> varEMA1v3 { get; set; }
        public Nullable<double> varEMA1v4 { get; set; }
        public Nullable<double> varEMA2v3 { get; set; }
        public Nullable<double> varEMA2v4 { get; set; }
        public Nullable<double> varEMA3v4 { get; set; }
        public Nullable<double> varEMA4v5 { get; set; }
        public Nullable<double> varVWMA1vVWMA2 { get; set; }
        public Nullable<double> varVWMA1vPriceClose { get; set; }
        public Nullable<double> varVWMA2vPriceClose { get; set; }
        public Nullable<double> varVWMA1vEMA1 { get; set; }
        public Nullable<double> varHAOvHAC { get; set; }
        public Nullable<double> varHAOvHAPO { get; set; }
        public Nullable<double> varHACvHAPC { get; set; }
        public Nullable<double> varOvC { get; set; }
        public Nullable<double> varOvPO { get; set; }
        public Nullable<double> varCvPC { get; set; }
        public string HAOCwEMA1 { get; set; }
        public string OCwEMA1 { get; set; }
        public string EMA2v34 { get; set; }
        public Nullable<int> AllEMAsInNum { get; set; }
    }
}
