//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradeGenie.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class TickerElderIndicator
    {
        public int InstrumentToken { get; set; }
        public System.DateTime TickerDateTime { get; set; }
        public int TimePeriod { get; set; }
        public string TradingSymbol { get; set; }
        public Nullable<double> PriceOpen { get; set; }
        public Nullable<double> PriceHigh { get; set; }
        public Nullable<double> PriceLow { get; set; }
        public Nullable<double> PriceClose { get; set; }
        public Nullable<int> Volume { get; set; }
        public Nullable<bool> IsCalculated { get; set; }
        public Nullable<double> EMA1 { get; set; }
        public Nullable<double> EMA2 { get; set; }
        public Nullable<double> EMA3 { get; set; }
        public Nullable<double> EMA4 { get; set; }
        public Nullable<double> MACD { get; set; }
        public double Signal { get; set; }
        public Nullable<double> Histogram { get; set; }
        public Nullable<double> AG1 { get; set; }
        public Nullable<double> AL1 { get; set; }
        public Nullable<double> RSI1 { get; set; }
        public Nullable<double> AG2 { get; set; }
        public Nullable<double> AL2 { get; set; }
        public Nullable<double> RSI2 { get; set; }
        public Nullable<double> ForceIndex { get; set; }
        public Nullable<double> OBV { get; set; }
        public Nullable<double> ATR { get; set; }
        public string Impulse { get; set; }
    }
}
