//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradeGenie.Repository
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class TradeGenieEntities : DbContext
    {
        public TradeGenieEntities()
            : base("name=TradeGenieEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ElderStrategyOrder> ElderStrategyOrders { get; set; }
        public virtual DbSet<Instrument> Instruments { get; set; }
        public virtual DbSet<Margin> Margins { get; set; }
        public virtual DbSet<MasterStockList> MasterStockLists { get; set; }
        public virtual DbSet<MorningBreakout> MorningBreakouts { get; set; }
        public virtual DbSet<NetPosition> NetPositions { get; set; }
        public virtual DbSet<OHLCData> OHLCDatas { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<Quote> Quotes { get; set; }
        public virtual DbSet<TickerElderIndicator> TickerElderIndicator { get; set; }
        public virtual DbSet<Trade> Trades { get; set; }
        public virtual DbSet<UserLogin> UserLogins { get; set; }
        public virtual DbSet<CamarillaStrategyOrder> CamarillaStrategyOrders { get; set; }
    
        public virtual ObjectResult<spGetOrders_Result> spGetOrders(Nullable<System.DateTime> dtDate)
        {
            var dtDateParameter = dtDate.HasValue ?
                new ObjectParameter("dtDate", dtDate) :
                new ObjectParameter("dtDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetOrders_Result>("spGetOrders", dtDateParameter);
        }
    }
}
