//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class GapStrategyPotentialOrder
    {
        public int Id { get; set; }
        public string StockCode { get; set; }
        public string Collection { get; set; }
        public Nullable<System.DateTime> Yesterday { get; set; }
        public Nullable<double> YesterdayClose { get; set; }
        public Nullable<System.DateTime> Today { get; set; }
        public Nullable<double> TodayOpen { get; set; }
        public Nullable<double> GapPer { get; set; }
        public string Position { get; set; }
        public Nullable<System.DateTime> BuyTime { get; set; }
        public Nullable<System.DateTime> SellTime { get; set; }
        public Nullable<System.DateTime> StopLossTime { get; set; }
        public Nullable<double> BuyPrice { get; set; }
        public Nullable<double> SellPrice { get; set; }
        public Nullable<double> StopLoss { get; set; }
        public Nullable<double> Target { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<double> MaxProfitAchieved { get; set; }
        public Nullable<double> MaxProfitCanBeAchieved { get; set; }
        public Nullable<double> PNL { get; set; }
    }
}
